We import what will serve us

In [3]:
from pandas import DataFrame, read_csv
import bigml.api
from bigml.api import BigML

We get the sumarry report field importances

In [4]:
field_importance1 = read_csv('field_importances/summarry_report_ensemble1_BigML_5db1710d7811dd7f2d0087fc_Ensemble_Field_Importances.csv')
field_importance2 = read_csv('field_importances/summarry_report_ensemble2_BigML_5db171aa5299631c82008cdc_Ensemble_Field_Importances.csv')
field_importance3 = read_csv('field_importances/summarry_report_ensemble3_BigML_5db17205e476847468009274_Ensemble_Field_Importances.csv')
field_importance4 = read_csv('field_importances/summarry_report_ensemble4_BigML_5db1737de4768474680092a4_Ensemble_Field_Importances.csv')
field_importance5 = read_csv('field_importances/summarry_report_ensemble5_BigML_5db1742e5299631c82008d25_Ensemble_Field_Importances.csv')
field_importance6 = read_csv('field_importances/summarry_report_ensemble6_BigML_5db174c57811dd7f2d00884b_Ensemble_Field_Importances.csv')

In [5]:
field_importance1

                                   Field  Importance
0                  WeightedOfLatePayment     0.22846
1   RevolvingUtilizationOfUnsecuredLines     0.21556
2                                    age     0.11136
3        NumberOfOpenCreditLinesAndLoans     0.08535
4                            MonthlyDebt     0.07562
5   NumberOfTime30-59DaysPastDueNotWorse     0.07353
6                       DisposableIncome     0.04642
7                              DebtRatio     0.04405
8           NumberRealEstateLoansOrLines     0.03094
9                          MonthlyIncome     0.02780
10                        BalancedIncome     0.02636
11                                field1     0.02624
12                    NumberOfDependents     0.00717
13  NumberOfTime60-89DaysPastDueNotWorse     0.00069
14               NumberOfTimes90DaysLate     0.00044

Maud SONET

we create a table with all the field importances

In [6]:
fields_importances = DataFrame()
fields_importances['Field'] = field_importance1['Field']
fields_importances['Importance_ens1'] = field_importance1['Importance']
fields_importances['Importance_ens2'] = field_importance2['Importance']
fields_importances['Importance_ens3'] = field_importance3['Importance']
fields_importances['Importance_ens4'] = field_importance4['Importance']
fields_importances['Importance_ens5'] = field_importance5['Importance']
fields_importances['Importance_ens6'] = field_importance6['Importance']
fields_importances

,Field,Importance_ens1,Importance_ens2,Importance_ens3,Importance_ens4,Importance_ens5,Importance_ens6
0,WeightedOfLatePayment,0.22846,0.22337,0.22028,0.29976,0.29332,0.20481
1,RevolvingUtilizationOfUnsecuredLines,0.21556,0.21646,0.21197,0.22591,0.22442,0.15562
2,age,0.11136,0.10676,0.11167,0.11496,0.10566,0.12694
3,NumberOfOpenCreditLinesAndLoans,0.08535,0.07359,0.08420,0.07437,0.08539,0.10183
4,MonthlyDebt,0.07562,0.07186,0.07517,0.06766,0.07288,0.09339
5,NumberOfTime30-59DaysPastDueNotWorse,0.07353,0.07060,0.07089,0.04330,0.04561,0.07594
6,DisposableIncome,0.04642,0.04393,0.04554,0.03586,0.04378,0.05877
7,DebtRatio,0.04405,0.04283,0.03969,0.03567,0.03808,0.04091
8,NumberRealEstateLoansOrLines,0.03094,0.03965,0.03459,0.03349,0.03163,0.03764
9,MonthlyIncome,0.02780,0.03870,0.03343,0.03076,0.02818,0.02651
10,BalancedIncome,0.02636,0.03152,0.03143,0.02413,0.02131,0.02457
11,field1,0.02624,0.02706,0.02733,0.01414,0.00971,0.02275
12,NumberOfDependents,0.00717,0.01142,0.00926,NaN,NaN,0.01947
13,NumberOfTime60-89DaysPastDueNotWorse,0.00069,0.00132,0.00333,NaN,NaN,0.01084
14,NumberOfTimes90DaysLate,0.00044,0.00091,0.00123,NaN,NaN,NaN

In [14]:
prediction_ensemble1 = read_csv('predictions/my_predictions1.csv')
prediction_ensemble2 = read_csv('predictions/my_predictions2.csv')
prediction_ensemble3 = read_csv('predictions/my_predictions3.csv')
prediction_ensemble4 = read_csv('predictions/my_predictions4.csv')
prediction_ensemble5 = read_csv('predictions/my_predictions5.csv')
prediction_ensemble6 = read_csv('predictions/my_predictions6.csv')
prediction_ensemble1

,field1,RevolvingUtilizationOfUnsecuredLines,age,DebtRatio,MonthlyIncome,MonthlyDebt,DisposableIncome,BalancedIncome,NumberOfOpenCreditLinesAndLoans,NumberRealEstateLoansOrLines,NumberOfTime30-59DaysPastDueNotWorse,NumberOfTime60-89DaysPastDueNotWorse,NumberOfTimes90DaysLate,WeightedOfLatePayment,NumberOfDependents,SeriousDlqin2yrs,SeriousDlqin2yrs.1
0,126550,0.021277,90,0.007094,3100,21.992907,3078.007093,3100.000000,6,0,0,0,0,0,0,0,0
1,35772,0.130125,58,0.204989,18000,3689.795016,14310.204984,6000.000000,9,2,0,0,0,0,2,0,0
2,12265,0.546874,55,0.452236,7400,3346.547762,4053.452238,2466.666667,11,2,0,0,0,0,2,0,0
3,55944,0.590389,63,0.545423,5800,3163.454577,2636.545423,5800.000000,7,1,2,0,0,2,0,0,0
4,65176,0.022841,70,0.300000,0,97.000000,0.000000,0.000000,10,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,140491,0.303038,41,0.159878,14116,2256.840121,11859.159879,2823.200000,7,1,0,0,0,0,4,0,0
29996,36589,0.024190,71,0.177031,10500,1858.822969,8641.177031,10500.000000,14,2,1,0,0,1,0,0,0
29997,39804,1.000000,79,0.039920,500,19.960080,480.039920,500.000000,2,0,0,0,0,0,0,0,0
29998,69360,0.262211,58,0.554313,11000,6097.445684,4902.554316,3666.666667,19,3,1,0,0,1,2,0,0
29999,124740,0.026587,61,0.338565,8346,2825.661437,5520.338563,2782.000000,9,1,0,0,0,0,2,0,0

In [35]:
TP_lines = (prediction_ensemble1['SeriousDlqin2yrs']==1) & (prediction_ensemble1['SeriousDlqin2yrs.1']==1)
TN_lines = ~(prediction_ensemble1['SeriousDlqin2yrs']==1) & ~(prediction_ensemble1['SeriousDlqin2yrs.1']==1)
FP_lines = ~(prediction_ensemble1['SeriousDlqin2yrs']==1) & (prediction_ensemble1['SeriousDlqin2yrs.1']==1)
FN_lines = (prediction_ensemble1['SeriousDlqin2yrs']==1) & ~(prediction_ensemble1['SeriousDlqin2yrs.1']==1)

TP = len(prediction_ensemble1.loc[TP_lines])
TN = len(prediction_ensemble1.loc[TN_lines])
FP = len(prediction_ensemble1.loc[FP_lines])
FN = len(prediction_ensemble1.loc[FN_lines])
print(f'TP={TP}')
print(f'TN={TN}')
print(f'FP={FP}')
print(f'FN={FN}')

TP=360
TN=27785
FP=197
FN=1658

In [36]:
TP_lines = (prediction_ensemble2['SeriousDlqin2yrs']==1) & (prediction_ensemble2['SeriousDlqin2yrs.1']==1)
TN_lines = ~(prediction_ensemble2['SeriousDlqin2yrs']==1) & ~(prediction_ensemble2['SeriousDlqin2yrs.1']==1)
FP_lines = ~(prediction_ensemble2['SeriousDlqin2yrs']==1) & (prediction_ensemble2['SeriousDlqin2yrs.1']==1)
FN_lines = (prediction_ensemble2['SeriousDlqin2yrs']==1) & ~(prediction_ensemble2['SeriousDlqin2yrs.1']==1)

TP = len(prediction_ensemble2.loc[TP_lines])
TN = len(prediction_ensemble2.loc[TN_lines])
FP = len(prediction_ensemble2.loc[FP_lines])
FN = len(prediction_ensemble2.loc[FN_lines])
print(f'TP={TP}')
print(f'TN={TN}')
print(f'FP={FP}')
print(f'FN={FN}')

TP=405
TN=27703
FP=282
FN=1610

In [37]:
TP_lines = (prediction_ensemble3['SeriousDlqin2yrs']==1) & (prediction_ensemble3['SeriousDlqin2yrs.1']==1)
TN_lines = ~(prediction_ensemble3['SeriousDlqin2yrs']==1) & ~(prediction_ensemble3['SeriousDlqin2yrs.1']==1)
FP_lines = ~(prediction_ensemble3['SeriousDlqin2yrs']==1) & (prediction_ensemble3['SeriousDlqin2yrs.1']==1)
FN_lines = (prediction_ensemble3['SeriousDlqin2yrs']==1) & ~(prediction_ensemble3['SeriousDlqin2yrs.1']==1)

TP = len(prediction_ensemble3.loc[TP_lines])
TN = len(prediction_ensemble3.loc[TN_lines])
FP = len(prediction_ensemble3.loc[FP_lines])
FN = len(prediction_ensemble3.loc[FN_lines])
print(f'TP={TP}')
print(f'TN={TN}')
print(f'FP={FP}')
print(f'FN={FN}')

TP=342
TN=27842
FP=204
FN=1612

In [38]:
TP_lines = (prediction_ensemble4['SeriousDlqin2yrs']==1) & (prediction_ensemble4['SeriousDlqin2yrs.1']==1)
TN_lines = ~(prediction_ensemble4['SeriousDlqin2yrs']==1) & ~(prediction_ensemble4['SeriousDlqin2yrs.1']==1)
FP_lines = ~(prediction_ensemble4['SeriousDlqin2yrs']==1) & (prediction_ensemble4['SeriousDlqin2yrs.1']==1)
FN_lines = (prediction_ensemble4['SeriousDlqin2yrs']==1) & ~(prediction_ensemble4['SeriousDlqin2yrs.1']==1)

TP = len(prediction_ensemble4.loc[TP_lines])
TN = len(prediction_ensemble4.loc[TN_lines])
FP = len(prediction_ensemble4.loc[FP_lines])
FN = len(prediction_ensemble4.loc[FN_lines])
print(f'TP={TP}')
print(f'TN={TN}')
print(f'FP={FP}')
print(f'FN={FN}')

TP=389
TN=27773
FP=230
FN=1608

In [40]:
TP_lines = (prediction_ensemble5['SeriousDlqin2yrs']==1) & (prediction_ensemble5['SeriousDlqin2yrs.1']==1)
TN_lines = ~(prediction_ensemble5['SeriousDlqin2yrs']==1) & ~(prediction_ensemble5['SeriousDlqin2yrs.1']==1)
FP_lines = ~(prediction_ensemble5['SeriousDlqin2yrs']==1) & (prediction_ensemble5['SeriousDlqin2yrs.1']==1)
FN_lines = (prediction_ensemble5['SeriousDlqin2yrs']==1) & ~(prediction_ensemble5['SeriousDlqin2yrs.1']==1)

TP = len(prediction_ensemble5.loc[TP_lines])
TN = len(prediction_ensemble5.loc[TN_lines])
FP = len(prediction_ensemble5.loc[FP_lines])
FN = len(prediction_ensemble5.loc[FN_lines])
print(f'TP={TP}')
print(f'TN={TN}')
print(f'FP={FP}')
print(f'FN={FN}')

TP=370
TN=27656
FP=286
FN=1688

In [41]:
TP_lines = (prediction_ensemble6['SeriousDlqin2yrs']==1) & (prediction_ensemble6['SeriousDlqin2yrs.1']==1)
TN_lines = ~(prediction_ensemble6['SeriousDlqin2yrs']==1) & ~(prediction_ensemble6['SeriousDlqin2yrs.1']==1)
FP_lines = ~(prediction_ensemble6['SeriousDlqin2yrs']==1) & (prediction_ensemble6['SeriousDlqin2yrs.1']==1)
FN_lines = (prediction_ensemble6['SeriousDlqin2yrs']==1) & ~(prediction_ensemble6['SeriousDlqin2yrs.1']==1)

TP = len(prediction_ensemble6.loc[TP_lines])
TN = len(prediction_ensemble6.loc[TN_lines])
FP = len(prediction_ensemble6.loc[FP_lines])
FN = len(prediction_ensemble6.loc[FN_lines])
print(f'TP={TP}')
print(f'TN={TN}')
print(f'FP={FP}')
print(f'FN={FN}')

TP=347
TN=27721
FP=252
FN=1680